import React from "react";

const SurrogateKeys: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Surrogate Keys
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 15 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Surrogate keys are system-generated, meaningless integer identifiers used as primary
      keys in dimension tables. They replace natural keys from source systems and are a
      fundamental concept in dimensional modeling.
    </p>

    {/* What are Surrogate Keys */}
    <h2 className="text-3xl font-bold mt-8">What are Surrogate Keys?</h2>
    <div className="bg-gray-100 text-gray-900 p-6 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Surrogate Keys vs Natural Keys:
════════════════════════════════════════════════════════════════

NATURAL KEY (Business Key):              SURROGATE KEY:
─────────────────────────                ──────────────
• Comes from source system               • Generated by data warehouse
• Has business meaning                   • No business meaning
• Can change over time                   • Never changes
• May be composite                       • Always single column
• Various data types                     • Always integer

Example:

Source System (Natural Keys):
┌─────────────┬──────────────┬─────────────┐
│ employee_id │ name         │ department  │
│   (Natural) │              │             │
├─────────────┼──────────────┼─────────────┤
│ EMP-2024-001│ John Smith   │ Sales       │
│ E/NY/00542  │ Jane Doe     │ Marketing   │  ← Various formats!
│ 78923       │ Bob Wilson   │ IT          │
└─────────────┴──────────────┴─────────────┘

Data Warehouse (Surrogate Keys):
┌─────────────┬─────────────┬──────────────┬─────────────┐
│ employee_key│ employee_id │ name         │ department  │
│ (Surrogate) │ (Natural)   │              │             │
├─────────────┼─────────────┼──────────────┼─────────────┤
│ 1           │ EMP-2024-001│ John Smith   │ Sales       │
│ 2           │ E/NY/00542  │ Jane Doe     │ Marketing   │
│ 3           │ 78923       │ Bob Wilson   │ IT          │
└─────────────┴─────────────┴──────────────┴─────────────┘
      │
      └── Simple, consistent, integer keys`}
      </pre>
    </div>

    {/* Why Use Surrogate Keys */}
    <h2 className="text-3xl font-bold mt-8">Why Use Surrogate Keys?</h2>
    <div className="space-y-4 mt-4">
      <div className="p-4 border rounded-lg">
        <h3 className="font-bold text-lg mb-2">1. Source System Independence</h3>
        <p className="text-sm">Surrogate keys isolate the data warehouse from changes in source system key structures. If a source system changes its ID format, the warehouse remains unaffected.</p>
      </div>
      <div className="p-4 border rounded-lg">
        <h3 className="font-bold text-lg mb-2">2. Handle Multiple Sources</h3>
        <p className="text-sm">When integrating data from multiple systems, natural keys may conflict. Surrogate keys provide a unified identifier across all sources.</p>
      </div>
      <div className="p-4 border rounded-lg">
        <h3 className="font-bold text-lg mb-2">3. Support SCD Type 2</h3>
        <p className="text-sm">Essential for tracking history. Multiple surrogate keys can exist for the same natural key, representing different versions over time.</p>
      </div>
      <div className="p-4 border rounded-lg">
        <h3 className="font-bold text-lg mb-2">4. Performance Optimization</h3>
        <p className="text-sm">Integer keys are smaller and faster for joins compared to composite or string-based natural keys.</p>
      </div>
      <div className="p-4 border rounded-lg">
        <h3 className="font-bold text-lg mb-2">5. Handle NULL and Unknown</h3>
        <p className="text-sm">Special surrogate key values (like 0 or -1) can represent unknown or not applicable records without NULL complications.</p>
      </div>
    </div>

    {/* SCD Type 2 Example */}
    <h2 className="text-3xl font-bold mt-8">Surrogate Keys with SCD Type 2</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`SCD Type 2 - Multiple Surrogate Keys for Same Natural Key:
════════════════════════════════════════════════════════════════

CUSTOMER_DIM Table:
┌──────────────┬─────────────┬───────────┬────────────┬────────────┬─────────┐
│ customer_key │ customer_id │ name      │ city       │ start_date │ current │
│ (Surrogate)  │ (Natural)   │           │            │            │         │
├──────────────┼─────────────┼───────────┼────────────┼────────────┼─────────┤
│ 1001         │ CUST-500    │ John Doe  │ New York   │ 2020-01-01 │ N       │
│ 1002         │ CUST-500    │ John Doe  │ Chicago    │ 2022-06-15 │ N       │
│ 1003         │ CUST-500    │ John Doe  │ Los Angeles│ 2024-03-01 │ Y       │
└──────────────┴─────────────┴───────────┴────────────┴────────────┴─────────┘
       │              │
       │              └── Same natural key (customer)
       │
       └── Different surrogate keys (one per version)

SALES_FACT Table:
┌──────────────┬───────────┬─────────┐
│ customer_key │ date_key  │ amount  │
├──────────────┼───────────┼─────────┤
│ 1001         │ 20210115  │ 150.00  │ ← Sale when customer in New York
│ 1002         │ 20230720  │ 275.00  │ ← Sale when customer in Chicago
│ 1003         │ 20260110  │ 89.99   │ ← Sale when customer in LA
└──────────────┴───────────┴─────────┘

Each sale links to the correct customer version!`}
      </pre>
    </div>

    {/* Generation Methods */}
    <h2 className="text-3xl font-bold mt-8">Surrogate Key Generation Methods</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Method</th>
            <th className="p-3 border">Description</th>
            <th className="p-3 border">Pros/Cons</th>
          </tr>
        </thead>
        <tbody className="dark:bg-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Database Sequence</td>
            <td className="p-3 border">AUTO_INCREMENT, IDENTITY, SEQUENCE</td>
            <td className="p-3 border">Simple; DB-dependent</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">ETL Max+1</td>
            <td className="p-3 border">Query MAX(key) + 1 during ETL</td>
            <td className="p-3 border">Portable; concurrency issues</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Key Table</td>
            <td className="p-3 border">Dedicated table tracks next key per dimension</td>
            <td className="p-3 border">Controlled; extra table needed</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Hash-based</td>
            <td className="p-3 border">Hash of natural key (deterministic)</td>
            <td className="p-3 border">Repeatable; potential collisions</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">GUID/UUID</td>
            <td className="p-3 border">Universally unique identifier</td>
            <td className="p-3 border">Globally unique; larger size</td>
          </tr>
        </tbody>
      </table>
    </div>

    {/* SQL Examples */}
    <h2 className="text-3xl font-bold mt-8">SQL Generation Examples</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Surrogate Key Generation Methods:
════════════════════════════════════════════════════════════════

-- Method 1: Database AUTO_INCREMENT (MySQL)
CREATE TABLE customer_dim (
    customer_key INT AUTO_INCREMENT PRIMARY KEY,
    customer_id VARCHAR(50),
    customer_name VARCHAR(100)
);

-- Method 2: IDENTITY (SQL Server)
CREATE TABLE customer_dim (
    customer_key INT IDENTITY(1,1) PRIMARY KEY,
    customer_id VARCHAR(50),
    customer_name VARCHAR(100)
);

-- Method 3: SEQUENCE (PostgreSQL/Oracle)
CREATE SEQUENCE customer_key_seq START 1;

INSERT INTO customer_dim (customer_key, customer_id, customer_name)
VALUES (NEXTVAL('customer_key_seq'), 'CUST-001', 'John Doe');

-- Method 4: ETL Lookup/Generate Pattern
-- During ETL, lookup existing or generate new:

-- Check if natural key exists
SELECT customer_key FROM customer_dim
WHERE customer_id = 'CUST-001' AND is_current = 'Y';

-- If not found, generate new:
INSERT INTO customer_dim (customer_key, ...)
SELECT COALESCE(MAX(customer_key), 0) + 1, ...
FROM customer_dim;`}
      </pre>
    </div>

    {/* Special Surrogate Keys */}
    <h2 className="text-3xl font-bold mt-8">Special Surrogate Key Values</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Special Surrogate Keys for Edge Cases:
════════════════════════════════════════════════════════════════

CUSTOMER_DIM with Special Keys:
┌──────────────┬─────────────┬────────────────────────────────┐
│ customer_key │ customer_id │ description                    │
├──────────────┼─────────────┼────────────────────────────────┤
│ -1           │ UNKNOWN     │ Customer is unknown            │
│ 0            │ N/A         │ Not applicable (e.g., returns) │
│ -2           │ NOT_YET     │ Record not yet loaded          │
│ 1            │ CUST-001    │ First actual customer          │
│ 2            │ CUST-002    │ Second actual customer         │
│ ...          │ ...         │ ...                            │
└──────────────┴─────────────┴────────────────────────────────┘

DATE_DIM with Special Keys:
┌──────────┬────────────┬────────────────────────────────────┐
│ date_key │ date_value │ description                        │
├──────────┼────────────┼────────────────────────────────────┤
│ -1       │ 1900-01-01 │ Unknown date                       │
│ 0        │ 1900-01-02 │ Not applicable                     │
│ 99991231 │ 9999-12-31 │ Far future (current SCD end date)  │
│ 20260115 │ 2026-01-15 │ Actual date (smart key format)     │
└──────────┴────────────┴────────────────────────────────────┘

Benefits:
• Avoids NULL foreign keys in fact tables
• Provides meaningful reports for unknown/N/A cases
• Maintains referential integrity`}
      </pre>
    </div>

    {/* Comparison Table */}
    <h2 className="text-3xl font-bold mt-8">Natural vs Surrogate Keys Comparison</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Aspect</th>
            <th className="p-3 border">Natural Key</th>
            <th className="p-3 border">Surrogate Key</th>
          </tr>
        </thead>
        <tbody className="dark:bg-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Source</td>
            <td className="p-3 border">Business/source system</td>
            <td className="p-3 border">DW system-generated</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Meaning</td>
            <td className="p-3 border">Business meaning</td>
            <td className="p-3 border">No meaning</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Stability</td>
            <td className="p-3 border">Can change</td>
            <td className="p-3 border">Never changes</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Data Type</td>
            <td className="p-3 border">Varies (string, composite)</td>
            <td className="p-3 border">Integer</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Size</td>
            <td className="p-3 border">Often larger</td>
            <td className="p-3 border">Compact (4 bytes)</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">SCD Type 2</td>
            <td className="p-3 border">Cannot support alone</td>
            <td className="p-3 border">Essential for support</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Multi-source</td>
            <td className="p-3 border">May conflict</td>
            <td className="p-3 border">Unified</td>
          </tr>
        </tbody>
      </table>
    </div>

    {/* Best Practices */}
    <h2 className="text-3xl font-bold mt-8">Best Practices</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2 mt-4">
      <li><strong>Always use surrogate keys</strong> as primary keys in dimension tables</li>
      <li><strong>Keep natural keys</strong> for reference and source system lookups</li>
      <li><strong>Use integers</strong> for surrogate keys (smallest sufficient size)</li>
      <li><strong>Create special keys</strong> for unknown (-1) and not applicable (0)</li>
      <li><strong>Never expose surrogate keys</strong> to business users in reports</li>
      <li><strong>Generate sequentially</strong> for better index performance</li>
      <li><strong>Document key meanings</strong> especially for special values</li>
    </ul>

    {/* Key Points */}
    <h2 className="text-3xl font-bold mt-8">Key Points to Remember</h2>
    <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg mt-4">
      <ul className="list-disc list-inside leading-relaxed space-y-2">
        <li>Surrogate keys are system-generated, meaningless integer identifiers</li>
        <li>They replace natural keys as primary keys in dimension tables</li>
        <li>Essential for source system independence and SCD Type 2</li>
        <li>Enable integration of data from multiple source systems</li>
        <li>Provide better join performance than natural keys</li>
        <li>Special values handle unknown and not applicable cases</li>
        <li>Natural keys should still be stored for reference</li>
        <li>Surrogate keys should never be exposed to end users</li>
      </ul>
    </div>
  </div>
);

export default SurrogateKeys;
