import React from 'react';

const LogicalVsPhysicalAddress: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Logical vs Physical Address
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 12 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Understanding the difference between logical and physical addresses is fundamental to understanding
      how memory management works in operating systems. These two types of addresses represent different
      views of memory: the programmer's view and the actual hardware view.
    </p>

    {/* Logical Address */}
    <h2 className="text-3xl font-bold mt-8">Logical Address (Virtual Address)</h2>
    <p className="leading-relaxed">
      A logical address is generated by the CPU during program execution. It is also called a virtual
      address because it does not physically exist in memory. The logical address is the address that
      the process sees and uses.
    </p>
    <ul className="list-disc list-inside leading-relaxed space-y-1 mt-3">
      <li>Generated by the CPU during program execution</li>
      <li>Used by the process to reference memory locations</li>
      <li>Also known as virtual address</li>
      <li>Independent of actual physical memory location</li>
      <li>The set of all logical addresses is called the logical address space</li>
    </ul>

    {/* Physical Address */}
    <h2 className="text-3xl font-bold mt-8">Physical Address</h2>
    <p className="leading-relaxed">
      A physical address is the actual address in main memory (RAM). It is the address that the memory
      unit sees and uses to access data. The physical address is what the hardware uses to access
      memory locations.
    </p>
    <ul className="list-disc list-inside leading-relaxed space-y-1 mt-3">
      <li>Actual location in physical memory (RAM)</li>
      <li>Seen and used by the memory unit</li>
      <li>Corresponds to a real memory cell</li>
      <li>The set of all physical addresses is called the physical address space</li>
    </ul>

    {/* Comparison Table */}
    <h2 className="text-3xl font-bold mt-8">Comparison: Logical vs Physical Address</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Aspect</th>
            <th className="p-3 border">Logical Address</th>
            <th className="p-3 border">Physical Address</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Definition</td>
            <td className="p-3 border">Address generated by CPU</td>
            <td className="p-3 border">Address seen by memory unit</td>
          </tr>
          <tr>
            <td className="p-3 border">Visibility</td>
            <td className="p-3 border">Visible to user/programmer</td>
            <td className="p-3 border">Not directly visible to user</td>
          </tr>
          <tr>
            <td className="p-3 border">Generated By</td>
            <td className="p-3 border">CPU</td>
            <td className="p-3 border">Memory Management Unit (MMU)</td>
          </tr>
          <tr>
            <td className="p-3 border">Access</td>
            <td className="p-3 border">User can access using this address</td>
            <td className="p-3 border">User cannot directly access</td>
          </tr>
          <tr>
            <td className="p-3 border">Existence</td>
            <td className="p-3 border">Does not exist physically</td>
            <td className="p-3 border">Exists in physical memory</td>
          </tr>
          <tr>
            <td className="p-3 border">Also Known As</td>
            <td className="p-3 border">Virtual Address</td>
            <td className="p-3 border">Real Address</td>
          </tr>
        </tbody>
      </table>
    </div>

    {/* Memory Management Unit */}
    <h2 className="text-3xl font-bold mt-8">Memory Management Unit (MMU)</h2>
    <p className="leading-relaxed">
      The MMU is a hardware component that handles the translation from logical to physical addresses.
      It sits between the CPU and memory, converting every logical address to its corresponding physical
      address at runtime.
    </p>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
┌─────────┐     Logical      ┌─────────┐     Physical     ┌─────────┐
│   CPU   │ ───Address───►   │   MMU   │ ───Address───►   │ Memory  │
└─────────┘                  └─────────┘                  └─────────┘
                                  │
                                  │ Uses:
                                  │ - Relocation Register
                                  │ - Page Tables
                                  │ - Segment Tables
                                  │ - TLB
`}
      </pre>
    </div>

    {/* Address Translation with Relocation Register */}
    <h2 className="text-3xl font-bold mt-8">Address Translation (Simple Scheme)</h2>
    <p className="leading-relaxed">
      In the simplest scheme, the MMU uses a relocation register. The value in the relocation register
      is added to every logical address to produce the physical address.
    </p>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Physical Address = Logical Address + Relocation Register

Example:
- Relocation Register = 14000
- Logical Address from CPU = 346

Physical Address = 346 + 14000 = 14346

┌───────────────────────────────────────────────────────────┐
│                                                           │
│    CPU                MMU                 Memory          │
│   ┌───┐            ┌──────┐                               │
│   │346├──────────► │  +   │──────────► Access 14346       │
│   └───┘            └──┬───┘                               │
│     Logical           │                                   │
│     Address    ┌──────┴──────┐                            │
│                │ Relocation  │                            │
│                │   14000     │                            │
│                └─────────────┘                            │
└───────────────────────────────────────────────────────────┘
`}
      </pre>
    </div>

    {/* Logical Address Space */}
    <h2 className="text-3xl font-bold mt-8">Logical Address Space</h2>
    <p className="leading-relaxed">
      The logical address space is the set of all logical addresses generated by a program. Its size
      is determined by the word size of the CPU.
    </p>
    <ul className="list-disc list-inside leading-relaxed space-y-1 mt-3">
      <li><strong>For 32-bit CPU:</strong> Logical address space = 2^32 = 4 GB</li>
      <li><strong>For 64-bit CPU:</strong> Logical address space = 2^64 (theoretically 16 exabytes)</li>
      <li>Each process has its own logical address space</li>
      <li>Logical address space starts from 0 for each process</li>
    </ul>

    {/* Physical Address Space */}
    <h2 className="text-3xl font-bold mt-8">Physical Address Space</h2>
    <p className="leading-relaxed">
      The physical address space is the set of all physical addresses corresponding to the logical
      addresses. Its size is determined by the amount of physical memory (RAM) installed.
    </p>
    <ul className="list-disc list-inside leading-relaxed space-y-1 mt-3">
      <li>Determined by actual RAM installed in the system</li>
      <li>Example: 8 GB RAM = 2^33 bytes of physical address space</li>
      <li>Shared among all processes</li>
      <li>Managed by the operating system</li>
    </ul>

    {/* Compile Time vs Load Time vs Execution Time Binding */}
    <h2 className="text-3xl font-bold mt-8">When are Addresses Same or Different?</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Binding Time</th>
            <th className="p-3 border">Logical = Physical?</th>
            <th className="p-3 border">Explanation</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Compile Time</td>
            <td className="p-3 border">Yes (Same)</td>
            <td className="p-3 border">Absolute addresses generated at compile time</td>
          </tr>
          <tr>
            <td className="p-3 border">Load Time</td>
            <td className="p-3 border">Yes (Same)</td>
            <td className="p-3 border">Relocatable code, addresses fixed at load time</td>
          </tr>
          <tr>
            <td className="p-3 border">Execution Time</td>
            <td className="p-3 border">No (Different)</td>
            <td className="p-3 border">Dynamic binding, addresses translated by MMU</td>
          </tr>
        </tbody>
      </table>
    </div>

    {/* Example Calculation */}
    <h2 className="text-3xl font-bold mt-8">Example: Address Space Calculation</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Given:
- Logical Address Size: 16 bits
- Physical Memory: 64 KB
- Word Size: 1 byte

Calculations:

Logical Address Space:
= 2^16 addresses
= 65,536 bytes
= 64 KB

Physical Address Space:
= 64 KB (given)
= 2^16 bytes

Number of bits needed for Physical Address:
= log2(64 KB)
= log2(64 × 1024)
= log2(65,536)
= 16 bits
`}
      </pre>
    </div>

    {/* Benefits of Logical-Physical Separation */}
    <h2 className="text-3xl font-bold mt-8">Benefits of Separating Logical and Physical Addresses</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2">
      <li>
        <strong>Memory Protection:</strong> Each process works in its own logical address space,
        preventing interference with other processes.
      </li>
      <li>
        <strong>Relocation:</strong> Processes can be loaded at any location in physical memory
        without modification.
      </li>
      <li>
        <strong>Virtual Memory:</strong> Logical address space can be larger than physical memory,
        enabling virtual memory implementation.
      </li>
      <li>
        <strong>Sharing:</strong> Multiple logical addresses can map to the same physical address
        for efficient memory sharing.
      </li>
      <li>
        <strong>Simplified Programming:</strong> Programmers work with simple logical addresses
        without worrying about physical memory layout.
      </li>
    </ul>

    {/* Key Points */}
    <h2 className="text-3xl font-bold mt-8">Key Points</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-1">
      <li>Logical addresses are generated by the CPU; physical addresses are used by memory</li>
      <li>The MMU translates logical addresses to physical addresses</li>
      <li>Address binding at execution time requires hardware support (MMU)</li>
      <li>Logical and physical addresses are the same for compile-time and load-time binding</li>
      <li>Separation of address spaces enables protection, relocation, and virtual memory</li>
    </ul>
  </div>
);

export default LogicalVsPhysicalAddress;
