import React from 'react';

const Paging: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">

    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Paging in Memory Management
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 12 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Paging is a memory management scheme that eliminates the need for contiguous allocation of
      physical memory. It solves the external fragmentation problem by dividing physical memory
      into fixed-size blocks called frames and logical memory into blocks of the same size called pages.
    </p>

    {/* Basic Concepts */}
    <h2 className="text-3xl font-bold mt-8">Basic Concepts</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2">
      <li>
        <strong>Frame:</strong> Physical memory is divided into fixed-size blocks called frames.
      </li>
      <li>
        <strong>Page:</strong> Logical memory is divided into blocks of the same size called pages.
      </li>
      <li>
        <strong>Page Size = Frame Size:</strong> Both are always equal and typically a power of 2
        (e.g., 4 KB, 8 KB).
      </li>
      <li>
        <strong>Page Table:</strong> Maps pages to frames, maintained by the OS for each process.
      </li>
    </ul>

    {/* How Paging Works */}
    <h2 className="text-3xl font-bold mt-8">How Paging Works</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Logical Address Space              Physical Memory
(Process View)                     (Actual RAM)

┌─────────────┐                    ┌─────────────┐
│   Page 0    │────────────────────│   Frame 2   │  Frame 0
├─────────────┤                    ├─────────────┤
│   Page 1    │────────┐           │   Frame 5   │  Frame 1
├─────────────┤        │           ├─────────────┤
│   Page 2    │───┐    │           │   Page 0    │  Frame 2
├─────────────┤   │    │           ├─────────────┤
│   Page 3    │─┐ │    │           │   Frame 3   │  Frame 3
└─────────────┘ │ │    │           ├─────────────┤
                │ │    │           │   Page 3    │  Frame 4
                │ │    │           ├─────────────┤
                │ │    └──────────►│   Page 1    │  Frame 5
                │ │                ├─────────────┤
                │ └───────────────►│   Page 2    │  Frame 6
                │                  ├─────────────┤
                └─────────────────►│   Frame 7   │  Frame 7
                                   └─────────────┘

Pages can be placed in ANY available frame - no need for contiguous allocation!
`}
      </pre>
    </div>

    {/* Address Translation */}
    <h2 className="text-3xl font-bold mt-8">Address Translation</h2>
    <p className="leading-relaxed">
      Every logical address generated by the CPU is divided into two parts:
    </p>
    <ul className="list-disc list-inside leading-relaxed space-y-1 mt-3">
      <li><strong>Page Number (p):</strong> Used as an index into the page table</li>
      <li><strong>Page Offset (d):</strong> Combined with frame number to form physical address</li>
    </ul>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Logical Address Structure:
┌────────────────┬─────────────────┐
│  Page Number   │   Page Offset   │
│      (p)       │      (d)        │
└────────────────┴─────────────────┘
    m - n bits        n bits

Where:
- Total logical address bits = m
- Page size = 2^n bytes
- Number of pages = 2^(m-n)

Physical Address:
┌────────────────┬─────────────────┐
│  Frame Number  │   Frame Offset  │
│      (f)       │      (d)        │
└────────────────┴─────────────────┘
                      n bits

The offset (d) remains the same; only the page number is replaced with frame number.
`}
      </pre>
    </div>

    {/* Address Translation Process */}
    <h2 className="text-3xl font-bold mt-8">Address Translation Process</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
                    Logical Address
                    ┌─────┬─────┐
                    │  p  │  d  │
                    └──┬──┴─────┘
                       │
                       │ Page Number
                       ▼
        ┌────────────────────────────┐
        │        Page Table          │
        ├────────────────────────────┤
        │ Page 0 │ Frame 2           │
        │ Page 1 │ Frame 5           │──┐
        │ Page 2 │ Frame 6           │  │
        │ Page 3 │ Frame 4           │  │
        └────────────────────────────┘  │
                                        │
                    ┌───────────────────┘
                    │ Frame Number
                    ▼
            Physical Address
            ┌─────┬─────┐
            │  f  │  d  │
            └─────┴─────┘
`}
      </pre>
    </div>

    {/* Example Calculation */}
    <h2 className="text-3xl font-bold mt-8">Example: Address Translation</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Given:
- Logical Address Space: 16 bytes (4 bits)
- Page Size: 4 bytes (2 bits for offset)
- Physical Memory: 32 bytes (8 frames)
- Page Table: Page 0→Frame 5, Page 1→Frame 6, Page 2→Frame 1, Page 3→Frame 2

Translate Logical Address: 6 (binary: 0110)

Step 1: Split into page number and offset
- Address 6 = 0110 in binary
- Page number (upper 2 bits) = 01 = 1
- Page offset (lower 2 bits) = 10 = 2

Step 2: Look up page table
- Page 1 → Frame 6

Step 3: Form physical address
- Frame 6 = 110 in binary (3 bits)
- Physical Address = Frame Number + Offset
- Physical Address = 110 | 10 = 11010 = 26

Result: Logical Address 6 → Physical Address 26
`}
      </pre>
    </div>

    {/* More Complex Example */}
    <h2 className="text-3xl font-bold mt-8">Example: Page Table Calculation</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Given:
- Logical Address Space: 2^32 bytes (4 GB)
- Page Size: 4 KB = 2^12 bytes
- Physical Memory: 2^30 bytes (1 GB)

Calculate:

1. Number of bits for page offset:
   Page size = 4 KB = 2^12
   Offset bits = 12

2. Number of bits for page number:
   Total bits = 32
   Page number bits = 32 - 12 = 20

3. Number of pages:
   Pages = 2^20 = 1,048,576 pages (about 1 million)

4. Number of frames:
   Physical Memory / Frame Size = 2^30 / 2^12 = 2^18
   Frames = 262,144 frames

5. Page table size (if each entry is 4 bytes):
   Size = Number of pages × Entry size
   Size = 2^20 × 4 = 4 MB per process!
`}
      </pre>
    </div>

    {/* Hardware Support */}
    <h2 className="text-3xl font-bold mt-8">Hardware Support for Paging</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2">
      <li>
        <strong>Page Table Base Register (PTBR):</strong> Points to the page table in memory.
      </li>
      <li>
        <strong>Page Table Length Register (PTLR):</strong> Indicates the size of the page table.
      </li>
      <li>
        <strong>Translation Lookaside Buffer (TLB):</strong> High-speed cache for page table entries.
      </li>
    </ul>

    {/* Advantages */}
    <h2 className="text-3xl font-bold mt-8">Advantages of Paging</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-1">
      <li><strong>No External Fragmentation:</strong> Any free frame can hold any page</li>
      <li><strong>Simple Allocation:</strong> Just find any free frame(s)</li>
      <li><strong>Efficient Swapping:</strong> Pages can be swapped individually</li>
      <li><strong>Sharing:</strong> Pages can be shared between processes easily</li>
      <li><strong>Protection:</strong> Each page can have protection bits</li>
      <li><strong>No Compaction Needed:</strong> Memory is always fully utilized</li>
    </ul>

    {/* Disadvantages */}
    <h2 className="text-3xl font-bold mt-8">Disadvantages of Paging</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-1">
      <li><strong>Internal Fragmentation:</strong> Last page may not be fully utilized</li>
      <li><strong>Page Table Overhead:</strong> Page tables consume memory</li>
      <li><strong>Memory Access Time:</strong> Two memory accesses per reference (without TLB)</li>
      <li><strong>Page Table Size:</strong> Can be very large for large address spaces</li>
    </ul>

    {/* Internal Fragmentation in Paging */}
    <h2 className="text-3xl font-bold mt-8">Internal Fragmentation in Paging</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm text-gray-900">
{`
Example:
- Process size: 10,250 bytes
- Page size: 4 KB = 4,096 bytes

Pages needed:
- 10,250 / 4,096 = 2.5 pages
- Rounded up: 3 pages allocated

Internal fragmentation:
- Allocated: 3 × 4,096 = 12,288 bytes
- Needed: 10,250 bytes
- Wasted: 12,288 - 10,250 = 2,038 bytes

Average internal fragmentation = Page Size / 2
For 4 KB pages: average = 2 KB per process
`}
      </pre>
    </div>

    {/* Page Size Trade-offs */}
    <h2 className="text-3xl font-bold mt-8">Page Size Trade-offs</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Aspect</th>
            <th className="p-3 border">Small Pages</th>
            <th className="p-3 border">Large Pages</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Internal Fragmentation</td>
            <td className="p-3 border">Less</td>
            <td className="p-3 border">More</td>
          </tr>
          <tr>
            <td className="p-3 border">Page Table Size</td>
            <td className="p-3 border">Larger</td>
            <td className="p-3 border">Smaller</td>
          </tr>
          <tr>
            <td className="p-3 border">I/O Efficiency</td>
            <td className="p-3 border">Lower</td>
            <td className="p-3 border">Higher</td>
          </tr>
          <tr>
            <td className="p-3 border">TLB Efficiency</td>
            <td className="p-3 border">Lower</td>
            <td className="p-3 border">Higher</td>
          </tr>
        </tbody>
      </table>
    </div>

    {/* Key Points */}
    <h2 className="text-3xl font-bold mt-8">Key Points</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-1">
      <li>Paging divides physical memory into frames and logical memory into pages</li>
      <li>Page size equals frame size and is typically a power of 2</li>
      <li>Page table maps logical pages to physical frames</li>
      <li>Eliminates external fragmentation but has internal fragmentation</li>
      <li>Address translation requires looking up the page table</li>
      <li>TLB caches recently used page table entries for faster access</li>
      <li>Standard page sizes are 4 KB, 8 KB, or larger (huge pages)</li>
    </ul>
  </div>
);

export default Paging;
