import React from 'react';

const RegularProperties: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">Properties of Regular Languages</h1>
    <p className="text-sm text-gray-500">Last Updated: 16 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Regular languages have many important properties that make them well-suited for practical applications.
      Understanding these properties helps in designing efficient algorithms and proving language properties.
    </p>

    <h2 className="text-3xl font-bold mt-8">Characterizations of Regular Languages</h2>
    <p className="leading-relaxed">
      A language L is regular if and only if any of the following equivalent conditions hold:
    </p>
    <ul className="list-disc list-inside space-y-2 ml-4">
      <li>L is accepted by a DFA</li>
      <li>L is accepted by an NFA</li>
      <li>L is accepted by an e-NFA</li>
      <li>L is described by a regular expression</li>
      <li>L is generated by a regular grammar</li>
      <li>L has a finite Myhill-Nerode equivalence index</li>
    </ul>

    <h2 className="text-3xl font-bold mt-8">Closure Properties</h2>
    <p className="leading-relaxed">
      Regular languages are closed under many operations, meaning applying these operations to regular languages produces regular languages.
    </p>

    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Operation</th>
            <th className="p-3 border">Closed?</th>
            <th className="p-3 border">Construction</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Union</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Product construction or NFA union</td>
          </tr>
          <tr>
            <td className="p-3 border">Intersection</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Product construction</td>
          </tr>
          <tr>
            <td className="p-3 border">Complement</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Swap accepting/non-accepting in DFA</td>
          </tr>
          <tr>
            <td className="p-3 border">Concatenation</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">NFA concatenation</td>
          </tr>
          <tr>
            <td className="p-3 border">Kleene Star</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">NFA star construction</td>
          </tr>
          <tr>
            <td className="p-3 border">Reversal</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Reverse all transitions, swap start/accept</td>
          </tr>
          <tr>
            <td className="p-3 border">Homomorphism</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Replace symbols in RE</td>
          </tr>
          <tr>
            <td className="p-3 border">Inverse Homomorphism</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Modify DFA transitions</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Decision Properties</h2>
    <p className="leading-relaxed">
      Many important questions about regular languages can be answered algorithmically (are decidable).
    </p>

    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Problem</th>
            <th className="p-3 border">Decidable?</th>
            <th className="p-3 border">Algorithm</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Membership (w in L?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Run DFA on w</td>
          </tr>
          <tr>
            <td className="p-3 border">Emptiness (L = empty?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Check if any accept state is reachable</td>
          </tr>
          <tr>
            <td className="p-3 border">Finiteness (|L| finite?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Check for cycles on path to accept</td>
          </tr>
          <tr>
            <td className="p-3 border">Universality (L = Sigma*?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Check if complement is empty</td>
          </tr>
          <tr>
            <td className="p-3 border">Equivalence (L1 = L2?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Minimize both, check isomorphism</td>
          </tr>
          <tr>
            <td className="p-3 border">Inclusion (L1 subset L2?)</td>
            <td className="p-3 border">Yes</td>
            <td className="p-3 border">Check L1 intersect L2' = empty</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Complexity of Decision Problems</h2>
    <div className="bg-gray-100 text-gray-900 p-6 rounded-lg font-mono text-sm overflow-x-auto mt-4">
      <pre className="text-gray-900">{`For a DFA with n states and alphabet size k:

- Membership: O(|w|) time
- Emptiness: O(n) time (BFS/DFS from start)
- Finiteness: O(n) time (cycle detection)
- Universality: O(n) time (check complement emptiness)
- Equivalence: O(n log n) with Hopcroft's minimization

For NFA with n states:
- Membership: O(n^2 * |w|) or O(n * |w|) with caching
- May need to convert to DFA first (exponential worst case)

For Regular Expression of length m:
- Convert to NFA: O(m) time and space
- NFA has at most 2m states`}</pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Algebraic Properties</h2>
    <div className="bg-gray-100 text-gray-900 p-6 rounded-lg font-mono text-sm overflow-x-auto mt-4">
      <pre className="text-gray-900">{`Regular languages form a Boolean algebra:

1. Union is commutative and associative
2. Intersection is commutative and associative
3. Complement satisfies De Morgan's laws:
   (L1 U L2)' = L1' intersect L2'
   (L1 intersect L2)' = L1' U L2'

4. Distributive laws hold:
   L1 U (L2 intersect L3) = (L1 U L2) intersect (L1 U L3)
   L1 intersect (L2 U L3) = (L1 intersect L2) U (L1 intersect L3)

5. Identity elements:
   L U empty = L
   L intersect Sigma* = L

6. Complement properties:
   L U L' = Sigma*
   L intersect L' = empty
   (L')' = L`}</pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Non-Closure Properties</h2>
    <p className="leading-relaxed">
      Some operations do NOT preserve regularity when applied to regular and non-regular languages together:
    </p>
    <ul className="list-disc list-inside space-y-2 ml-4">
      <li>Intersection with CFL may not be regular (but is always CFL)</li>
      <li>Regular - CFL may not be regular</li>
    </ul>

    <div className="mt-8 p-6 bg-yellow-50 dark:bg-yellow-900/20 rounded-xl border border-yellow-200 dark:border-yellow-800">
      <h3 className="text-xl font-bold mb-3">Key Takeaways</h3>
      <ul className="list-disc list-inside space-y-1">
        <li>Regular languages have multiple equivalent characterizations</li>
        <li>Closed under union, intersection, complement, concatenation, star, reversal</li>
        <li>Membership, emptiness, equivalence are all decidable</li>
        <li>Form a Boolean algebra with union, intersection, complement</li>
        <li>Minimal DFA is unique and can be computed efficiently</li>
        <li>These properties make regular languages practical for many applications</li>
      </ul>
    </div>
  </div>
);

export default RegularProperties;
