import React from "react";

const SIEM: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      SIEM - Security Information and Event Management
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 17 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Security Information and Event Management (SIEM) is a solution that combines Security
      Information Management (SIM) and Security Event Management (SEM) to provide real-time
      analysis of security alerts generated by applications and network hardware. SIEM is
      the cornerstone of modern Security Operations Centers (SOC).
    </p>

    <h2 className="text-3xl font-bold mt-8">SIEM Architecture</h2>
    <div className="bg-gray-100 text-gray-900 p-6 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`SIEM System Architecture:

DATA SOURCES
+----------+  +----------+  +----------+  +----------+
| Firewall |  | IDS/IPS  |  |  Server  |  | Endpoint |
+----+-----+  +----+-----+  +----+-----+  +----+-----+
     |             |             |             |
     v             v             v             v
+------------------------------------------------------------------+
|                     LOG COLLECTION                                |
|  Syslog | Windows Events | API | Agents | NetFlow                |
+------------------------------------------------------------------+
                              |
                              v
+------------------------------------------------------------------+
|                     SIEM PLATFORM                                 |
|  +----------------+  +----------------+  +----------------+       |
|  | NORMALIZATION  |  |   INDEXING     |  |   STORAGE      |       |
|  | Parse & Format |  | Search Engine  |  | Hot/Warm/Cold  |       |
|  +----------------+  +----------------+  +----------------+       |
|                              |                                    |
|  +----------------+  +----------------+  +----------------+       |
|  |  CORRELATION   |  |   ALERTING     |  |  DASHBOARD     |       |
|  | Rule Matching  |  | Notifications  |  | Visualization  |       |
|  +----------------+  +----------------+  +----------------+       |
+------------------------------------------------------------------+
                              |
                              v
                    +------------------+
                    |   SOC ANALYST    |
                    +------------------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Core SIEM Functions</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Function</th>
            <th className="p-3 border">Description</th>
            <th className="p-3 border">Benefit</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Log Collection</td>
            <td className="p-3 border">Centralized log aggregation</td>
            <td className="p-3 border">Single source of truth</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Normalization</td>
            <td className="p-3 border">Convert to common format</td>
            <td className="p-3 border">Enable cross-source analysis</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Correlation</td>
            <td className="p-3 border">Link related events</td>
            <td className="p-3 border">Detect complex attacks</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Alerting</td>
            <td className="p-3 border">Real-time notifications</td>
            <td className="p-3 border">Rapid incident response</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Retention</td>
            <td className="p-3 border">Long-term log storage</td>
            <td className="p-3 border">Compliance, forensics</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Reporting</td>
            <td className="p-3 border">Automated reports</td>
            <td className="p-3 border">Compliance, metrics</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">SIEM Solutions</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Popular SIEM Solutions:

COMMERCIAL
+------------------+----------------------------------+
| Splunk           | Industry leader, powerful search |
| IBM QRadar       | Enterprise-grade, AI-powered    |
| Microsoft        | Cloud-native, Azure integration  |
|   Sentinel       |                                  |
| LogRhythm        | User-friendly, SOAR built-in    |
| Elastic SIEM     | Open-source core, flexible      |
| Exabeam          | UEBA focus, cloud-native        |
+------------------+----------------------------------+

OPEN SOURCE
+------------------+----------------------------------+
| Wazuh            | OSSEC fork, comprehensive        |
| Security Onion   | Network security monitoring     |
| ELK Stack        | Elasticsearch, Logstash, Kibana |
| OSSIM            | AlienVault open source          |
| Graylog          | Log management focused          |
+------------------+----------------------------------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Detection Rules</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`SIEM Detection Rule Examples:

1. BRUTE FORCE DETECTION
   Condition: >5 failed logins from same IP in 5 minutes
   Data Source: Authentication logs
   Severity: Medium
   Action: Alert + Block IP

2. LATERAL MOVEMENT
   Condition: Admin login from workstation to 5+ servers in 10 min
   Data Source: Windows Event Logs (4624)
   Severity: High
   Action: Alert + SOC investigation

3. DATA EXFILTRATION
   Condition: Outbound transfer >500MB to unknown IP
   Data Source: Firewall logs, NetFlow
   Severity: Critical
   Action: Alert + Block + Investigate

4. MALWARE INDICATOR
   Condition: Connection to known C2 domain
   Data Source: DNS logs, Proxy logs
   Severity: Critical
   Action: Isolate host + Alert

Rule Syntax Example (Sigma):
title: Multiple Failed Logins
status: production
logsource:
  category: authentication
detection:
  selection:
    EventType: Failed Login
  condition: selection | count() by src_ip > 5
  timeframe: 5m
level: medium`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Key Log Sources</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Source</th>
            <th className="p-3 border">Log Type</th>
            <th className="p-3 border">Use Cases</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Windows Servers</td>
            <td className="p-3 border">Security, System, Application</td>
            <td className="p-3 border">Login tracking, process execution</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Linux Servers</td>
            <td className="p-3 border">Syslog, auth.log, auditd</td>
            <td className="p-3 border">Authentication, commands</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Firewalls</td>
            <td className="p-3 border">Traffic logs, NAT logs</td>
            <td className="p-3 border">Network connections, blocks</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">IDS/IPS</td>
            <td className="p-3 border">Alert logs</td>
            <td className="p-3 border">Attack detection</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Web Servers</td>
            <td className="p-3 border">Access logs, error logs</td>
            <td className="p-3 border">Web attacks, access patterns</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Cloud Services</td>
            <td className="p-3 border">AWS CloudTrail, Azure AD</td>
            <td className="p-3 border">Cloud activity monitoring</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">SIEM Use Cases</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Common SIEM Use Cases:

THREAT DETECTION
- Malware infections
- Insider threats
- Brute force attacks
- Phishing campaigns
- Data exfiltration
- Privilege escalation

COMPLIANCE
- PCI DSS log monitoring
- HIPAA access tracking
- SOX audit trails
- GDPR data access logs
- Regulatory reporting

OPERATIONS
- System availability monitoring
- Performance metrics
- Change tracking
- Asset inventory
- Vulnerability correlation

INCIDENT RESPONSE
- Alert triage
- Investigation timeline
- Root cause analysis
- Impact assessment
- Evidence collection`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">SIEM Implementation Best Practices</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2 mt-2">
      <li><strong>Define Requirements:</strong> Identify use cases and compliance needs first</li>
      <li><strong>Prioritize Data Sources:</strong> Start with high-value logs (authentication, firewall)</li>
      <li><strong>Tune Correlation Rules:</strong> Reduce false positives through continuous tuning</li>
      <li><strong>Establish Baselines:</strong> Understand normal behavior before detecting anomalies</li>
      <li><strong>Plan Retention:</strong> Balance storage costs with compliance requirements</li>
      <li><strong>Train Analysts:</strong> Invest in SOC team skills and playbooks</li>
    </ul>

    <h2 className="text-3xl font-bold mt-8">Key Points to Remember</h2>
    <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg mt-4">
      <ul className="list-disc list-inside leading-relaxed space-y-2">
        <li>SIEM provides centralized visibility across the entire IT environment</li>
        <li>Correlation rules connect related events to detect complex attacks</li>
        <li>Log normalization is critical for effective cross-source analysis</li>
        <li>Continuous tuning reduces alert fatigue from false positives</li>
        <li>SIEM effectiveness depends on quality of data sources and rules</li>
        <li>Modern SIEM includes UEBA and SOAR capabilities</li>
      </ul>
    </div>
  </div>
);

export default SIEM;
