import React from "react";

const CFG: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Context-Free Grammars (CFG)
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 16 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      A <strong>Context-Free Grammar (CFG)</strong> is a formal system used to describe the
      syntax of programming languages. It provides production rules that specify how valid
      strings can be formed from the language's symbols.
    </p>

    <h2 className="text-3xl font-bold mt-8">Formal Definition</h2>
    <p className="leading-relaxed">
      A CFG is a 4-tuple G = (V, T, P, S) where:
    </p>
    <ul className="list-disc list-inside mt-2 space-y-1">
      <li><strong>V:</strong> Finite set of non-terminals (variables)</li>
      <li><strong>T:</strong> Finite set of terminals (tokens)</li>
      <li><strong>P:</strong> Finite set of production rules</li>
      <li><strong>S:</strong> Start symbol (S ∈ V)</li>
    </ul>

    <h2 className="text-3xl font-bold mt-8">Production Rules</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Production format: A → α

where:
- A is a non-terminal (left-hand side)
- α is a string of terminals and non-terminals (right-hand side)
- α can be empty (ε)

Multiple productions for same non-terminal:
A → α₁ | α₂ | ... | αₙ`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Example: Expression Grammar</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`G = (V, T, P, E)

V = {E, T, F}
T = {+, *, (, ), id}
S = E

Productions P:
  E → E + T | T
  T → T * F | F
  F → ( E ) | id

This grammar generates expressions like:
  id
  id + id
  id * id
  id + id * id
  (id + id) * id`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Why Context-Free?</h2>
    <p className="leading-relaxed">
      The grammar is called "context-free" because the left side of each production is a
      single non-terminal. The replacement can happen regardless of the context (surrounding symbols).
    </p>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Context-Free:    A → α      (A can be replaced by α anywhere)
Context-Sensitive: βAγ → βαγ (replacement depends on context β, γ)`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Notational Conventions</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Symbol</th>
            <th className="p-3 border">Meaning</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border font-mono text-gray-900">A, B, C, S</td>
            <td className="p-3 border">Non-terminals</td>
          </tr>
          <tr>
            <td className="p-3 border font-mono text-gray-900">a, b, c</td>
            <td className="p-3 border">Terminals</td>
          </tr>
          <tr>
            <td className="p-3 border font-mono text-gray-900">α, β, γ</td>
            <td className="p-3 border">Strings of symbols</td>
          </tr>
          <tr>
            <td className="p-3 border font-mono text-gray-900">ε</td>
            <td className="p-3 border">Empty string</td>
          </tr>
          <tr>
            <td className="p-3 border font-mono text-gray-900">→</td>
            <td className="p-3 border">Produces</td>
          </tr>
          <tr>
            <td className="p-3 border font-mono text-gray-900">|</td>
            <td className="p-3 border">Alternative</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Language of a Grammar</h2>
    <p className="leading-relaxed">
      The language L(G) generated by grammar G is the set of all strings of terminals
      derivable from the start symbol.
    </p>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`L(G) = { w ∈ T* | S ⇒* w }

where S ⇒* w means "S derives w in zero or more steps"`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">CFG Power</h2>
    <p className="leading-relaxed">CFGs can express:</p>
    <ul className="list-disc list-inside mt-2 space-y-1">
      <li>Nested structures (balanced parentheses)</li>
      <li>Block-structured programming constructs</li>
      <li>Recursive definitions</li>
      <li>Most programming language syntax</li>
    </ul>

    <h2 className="text-3xl font-bold mt-8">Key Takeaways</h2>
    <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg mt-4">
      <ul className="list-disc list-inside leading-relaxed space-y-2">
        <li>CFG is a 4-tuple (V, T, P, S)</li>
        <li>Productions have single non-terminal on left side</li>
        <li>"Context-free" means replacement is context-independent</li>
        <li>CFGs define syntax of programming languages</li>
        <li>The language L(G) is all derivable terminal strings</li>
      </ul>
    </div>
  </div>
);

export default CFG;
