import React from "react";

const DataFlowAnalysis: React.FC = () => (
  <div className="p-8 space-y-8 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Data Flow Analysis
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 17 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Data flow analysis is a technique for gathering information about the possible
      values and states at various points in a program. It forms the foundation
      for many optimizations by computing properties that hold for all possible
      execution paths.
    </p>

    <h2 className="text-3xl font-bold mt-8">What is Data Flow Analysis?</h2>
    <p className="leading-relaxed">
      Data flow analysis computes information at each program point by propagating
      facts along the edges of the control flow graph. It answers questions like
      "what values can reach this point?" or "is this expression available here?"
    </p>

    <div className="bg-gray-100 text-gray-900 p-6 rounded-lg mt-4 font-mono text-sm text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Data Flow Analysis Framework:

For each basic block B:
    IN[B]  = Information flowing INTO block B
    OUT[B] = Information flowing OUT OF block B

    +--------+
    | IN[B]  |  <-- Information from predecessors
    +---+----+
        |
        v
    +---+----+
    |   B    |  <-- Transfer function: OUT = f(IN)
    +---+----+
        |
        v
    +---+----+
    | OUT[B] |  <-- Information to successors
    +--------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Components of Data Flow Analysis</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Component</th>
            <th className="p-3 border">Description</th>
            <th className="p-3 border">Example</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Domain</td>
            <td className="p-3 border">Set of possible values</td>
            <td className="p-3 border">Sets of definitions, expressions</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Direction</td>
            <td className="p-3 border">Forward or backward</td>
            <td className="p-3 border">Entry to exit or exit to entry</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Transfer Function</td>
            <td className="p-3 border">How block transforms info</td>
            <td className="p-3 border">gen/kill sets</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Meet Operator</td>
            <td className="p-3 border">Combine info at join points</td>
            <td className="p-3 border">Union, intersection</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Boundary Values</td>
            <td className="p-3 border">Initial values at entry/exit</td>
            <td className="p-3 border">Empty set, universal set</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Forward vs Backward Analysis</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Forward Analysis (Entry -> Exit):
    Information flows in direction of execution
    IN[B] = Meet of OUT[predecessors]
    OUT[B] = Transfer(IN[B])

    Examples: Reaching Definitions, Available Expressions

    +--------+
    |  B1    | OUT[B1] ----+
    +--------+             |
                           v
    +--------+        +----+----+
    |  B2    | OUT[B2]-->  Meet  |--> IN[B4]
    +--------+        +---------+

Backward Analysis (Exit -> Entry):
    Information flows opposite to execution
    OUT[B] = Meet of IN[successors]
    IN[B] = Transfer(OUT[B])

    Examples: Live Variables, Very Busy Expressions`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Transfer Functions</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Transfer functions describe how information changes
through a basic block.

Gen/Kill Framework:
    OUT[B] = gen[B] U (IN[B] - kill[B])

gen[B]  = New facts generated by block B
kill[B] = Facts invalidated by block B

Example (Reaching Definitions):
    Block B:
        x = a + b    (definition d1)
        y = x * 2    (definition d2)

    gen[B]  = {d1, d2}  (new definitions)
    kill[B] = {all other defs of x, y}

    OUT[B] = {d1, d2} U (IN[B] - {other defs of x,y})`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Iterative Algorithm</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`Algorithm: Iterative Data Flow Analysis (Forward)

Input: CFG with gen/kill for each block
Output: IN[B] and OUT[B] for each block B

1. Initialize:
   OUT[Entry] = boundary value (e.g., empty set)
   OUT[B] = initial value for all other B

2. Repeat until no change:
   For each block B (except Entry):
       IN[B] = Meet over all predecessors P of OUT[P]
       OUT[B] = gen[B] U (IN[B] - kill[B])

3. Return IN and OUT for each block

Termination: Guaranteed because:
- Domain is finite
- Transfer functions are monotonic
- Meet operator produces smaller/larger values`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Example: Forward Analysis</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 font-mono text-gray-900">
      <pre className="whitespace-pre-wrap text-gray-900">
{`CFG:
         +--------+
         | Entry  |
         | d1:x=5 |
         +---+----+
             |
        +----+----+
        |         |
    +---v---+ +---v---+
    |  B2   | |  B3   |
    |d2:x=10| |d3:y=x |
    +---+---+ +---+---+
        |         |
        +----+----+
             |
         +---v---+
         |  B4   |
         | z = x |
         +-------+

Reaching Definitions Analysis:
    Iteration 1:
    IN[B2] = {d1}     OUT[B2] = {d2}
    IN[B3] = {d1}     OUT[B3] = {d1,d3}
    IN[B4] = {d2,d1,d3}

    Iteration 2: No change -> Fixed point

Result: At B4, x could be defined by d1 or d2`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Common Data Flow Analyses</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Analysis</th>
            <th className="p-3 border">Direction</th>
            <th className="p-3 border">Meet</th>
            <th className="p-3 border">Used For</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border font-semibold">Reaching Definitions</td>
            <td className="p-3 border">Forward</td>
            <td className="p-3 border">Union</td>
            <td className="p-3 border">Copy propagation</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Available Expressions</td>
            <td className="p-3 border">Forward</td>
            <td className="p-3 border">Intersection</td>
            <td className="p-3 border">CSE</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Live Variables</td>
            <td className="p-3 border">Backward</td>
            <td className="p-3 border">Union</td>
            <td className="p-3 border">Dead code, register alloc</td>
          </tr>
          <tr>
            <td className="p-3 border font-semibold">Very Busy Expressions</td>
            <td className="p-3 border">Backward</td>
            <td className="p-3 border">Intersection</td>
            <td className="p-3 border">Code hoisting</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Key Points to Remember</h2>
    <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg mt-4">
      <ul className="list-disc list-inside leading-relaxed space-y-2">
        <li>Data flow analysis propagates information along CFG edges</li>
        <li>Forward analysis flows from entry to exit; backward from exit to entry</li>
        <li>Transfer functions describe how blocks transform information</li>
        <li>Meet operator combines information at join points</li>
        <li>Iterative algorithm computes fixed point solution</li>
        <li>Different analyses use different domains and operators</li>
      </ul>
    </div>
  </div>
);

export default DataFlowAnalysis;
