import React from 'react';

const HardwiredControl: React.FC = () => (
  <div className="p-8 space-y-6 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Hardwired Control Unit
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 13 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      A Hardwired Control Unit is implemented using fixed combinational logic circuits
      that directly generate control signals based on the instruction opcode and timing signals.
      The control logic is physically wired using gates, flip-flops, and decoders, making it
      fast but inflexible. This approach is commonly used in RISC processors where the
      instruction set is simple and well-defined.
    </p>

    <h2 className="text-3xl font-bold mt-8">Characteristics of Hardwired Control</h2>
    <ul className="list-disc list-inside leading-relaxed space-y-2">
      <li><strong>Fixed Logic:</strong> Control signals are generated by permanent circuit connections</li>
      <li><strong>High Speed:</strong> No memory access required, direct signal generation</li>
      <li><strong>No Control Memory:</strong> Does not use microinstructions or control ROM</li>
      <li><strong>Complex Design:</strong> Requires careful logic design and optimization</li>
      <li><strong>Difficult Modification:</strong> Changes require hardware redesign</li>
      <li><strong>RISC Preference:</strong> Well-suited for simple, regular instruction sets</li>
    </ul>

    <h2 className="text-3xl font-bold mt-8">Hardwired Control Unit Architecture</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Hardwired Control Unit Block Diagram:

    +--------------------+
    |   Instruction      |
    |    Register        |
    |  +------+-------+  |
    |  |Opcode|Operand|  |
    |  +--+---+-------+  |
    +----|---------------+
         |
         v
    +----+---------------+
    |  Instruction       |
    |    Decoder         |
    | (n-to-2^n decoder) |
    +----+---------------+
         |
         | D0, D1, D2, ... D(2^n-1)
         v
    +----+---------------+     +------------------+
    |                    |     |                  |
    |   Combinational    |<----|  Timing Signals  |
    |   Logic Network    |     |  T0, T1, T2...   |
    |                    |     |                  |
    | (AND, OR, NOT      |     +------------------+
    |  gates network)    |            ^
    |                    |            |
    +----+---------------+     +------+------+
         |                     | Clock       |
         v                     | Generator   |
    +----+---------------+     +-------------+
    |  Control Signals   |
    |  C1, C2, C3, ...   |
    +--------------------+
         |
         v
    +----+---------------+
    |     Datapath       |
    |  (ALU, Registers,  |
    |   Memory, Buses)   |
    +--------------------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Components of Hardwired Control</h2>

    <h3 className="text-2xl font-semibold mt-6">1. Instruction Decoder</h3>
    <p className="leading-relaxed">
      A combinational circuit that decodes the opcode field of the instruction.
      For an n-bit opcode, it produces up to 2^n output lines, one for each possible instruction.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Instruction Decoder (4-bit opcode example):

Opcode bits: I3 I2 I1 I0

              +-------------------+
   I3 ------->|                   |-----> D0 (ADD)
   I2 ------->|   4-to-16         |-----> D1 (SUB)
   I1 ------->|   Decoder         |-----> D2 (AND)
   I0 ------->|                   |-----> D3 (OR)
              |                   |-----> D4 (LOAD)
              |                   |-----> D5 (STORE)
              |                   |-----> D6 (BRANCH)
              +-------------------+-----> ...D15

Decoder Truth Table:
+----+----+----+----+------+
| I3 | I2 | I1 | I0 |Output|
+----+----+----+----+------+
|  0 |  0 |  0 |  0 | D0=1 | ADD
|  0 |  0 |  0 |  1 | D1=1 | SUB
|  0 |  0 |  1 |  0 | D2=1 | AND
|  0 |  0 |  1 |  1 | D3=1 | OR
|  0 |  1 |  0 |  0 | D4=1 | LOAD
|  0 |  1 |  0 |  1 | D5=1 | STORE
|  0 |  1 |  1 |  0 | D6=1 | BRANCH
+----+----+----+----+------+`}
      </pre>
    </div>

    <h3 className="text-2xl font-semibold mt-6">2. Timing Generator</h3>
    <p className="leading-relaxed">
      Produces timing signals (T0, T1, T2, ...) that sequence the operations within
      each instruction cycle. Typically implemented using a counter and decoder.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Timing Signal Generator:

    +-------+     +--------+     +----------+
    | Clock |---->| Counter|---->| Decoder  |
    +-------+     | (mod n)|     +----------+
                  +--------+          |
                      |               +---> T0
                      |               +---> T1
                Reset |               +---> T2
                      ^               +---> T3
                      |               +---> T4
                 End of               +---> T5
                instruction

Timing Diagram:
    CLK   _|--|__|--|__|--|__|--|__|--|__|--|__

    T0    _|--|________________________________

    T1    ____|--|_____________________________

    T2    ________|--|_________________________

    T3    ____________|--|_____________________

    T4    ________________|--|_________________

    T5    ____________________|--|_____________

          <--- One Instruction Cycle --->`}
      </pre>
    </div>

    <h3 className="text-2xl font-semibold mt-6">3. Control Logic Matrix</h3>
    <p className="leading-relaxed">
      The combinational logic that combines instruction decoder outputs and timing
      signals to produce the required control signals.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Control Signal Generation:

Control Signal = f(Instruction, Timing, Flags)

Example: RegWrite signal
RegWrite is active during:
- T5 for ADD instruction
- T5 for SUB instruction
- T6 for LOAD instruction

Boolean Expression:
RegWrite = (D_ADD AND T5) OR (D_SUB AND T5) OR (D_LOAD AND T6)

Logic Circuit:
                 D_ADD ----+
                          AND ----+
                 T5 ------+       |
                                  |
                 D_SUB ----+      OR -----> RegWrite
                          AND ----+
                 T5 ------+       |
                                  |
                 D_LOAD ---+      |
                          AND ----+
                 T6 ------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Control Signal Equations</h2>
    <p className="leading-relaxed">
      Each control signal can be expressed as a Boolean equation combining
      instruction types and timing states.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Control Signal Boolean Equations:

Common to all instructions (Fetch Phase):
PCout    = T0
MARin    = T0
MemRead  = T1
MBRin    = T1
PCinc    = T1
MBRout   = T2
IRin     = T2

Instruction-Specific (Execute Phase):

For ADD R1, R2, R3:
R2out   = D_ADD AND T3
Ain     = D_ADD AND T3
R3out   = D_ADD AND T4
ALU_ADD = D_ADD AND T4
Zin     = D_ADD AND T4
Zout    = D_ADD AND T5
R1in    = D_ADD AND T5

For LOAD R1, addr:
AddrOut = D_LOAD AND T3
MARin   = D_LOAD AND T3
MemRead = D_LOAD AND T4
MBRin   = D_LOAD AND T4
MBRout  = D_LOAD AND T5
R1in    = D_LOAD AND T5

For STORE R1, addr:
R1out   = D_STORE AND T3
MBRin   = D_STORE AND T3
AddrOut = D_STORE AND T4
MARin   = D_STORE AND T4
MBRout  = D_STORE AND T5
MemWrite= D_STORE AND T5

For BRANCH addr (if Zero flag set):
AddrOut = D_BRANCH AND T3 AND Zero
PCin    = D_BRANCH AND T3 AND Zero`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Complete Hardwired Control Example</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Example: Simple CPU with 4 instructions

Instructions:
  0000 - ADD R1, R2    (R1 = R1 + R2)
  0001 - SUB R1, R2    (R1 = R1 - R2)
  0010 - LOAD R1, M    (R1 = Memory[M])
  0011 - STORE R1, M   (Memory[M] = R1)

Control Signal Matrix:

+--------+----+----+----+----+----+----+----+
|Signal  | T0 | T1 | T2 | T3 | T4 | T5 | T6 |
+--------+----+----+----+----+----+----+----+
|PCout   | 1  | 0  | 0  | 0  | 0  | 0  | 0  |
|MARin   | 1  | 0  | 0  | *  | *  | 0  | 0  |
|MemRead | 0  | 1  | 0  | 0  | *  | 0  | 0  |
|MBRin   | 0  | 1  | 0  | *  | *  | 0  | 0  |
|PCinc   | 0  | 1  | 0  | 0  | 0  | 0  | 0  |
|IRin    | 0  | 0  | 1  | 0  | 0  | 0  | 0  |
|ALUop   | 0  | 0  | 0  | 0  | *  | 0  | 0  |
|RegWrite| 0  | 0  | 0  | 0  | 0  | *  | 0  |
+--------+----+----+----+----+----+----+----+

* = Instruction dependent

Expanded Control Equations:

MARin = T0 + (D_LOAD * T3) + (D_STORE * T4)

MemRead = T1 + (D_LOAD * T4)

MBRin = T1 + (D_STORE * T3) + (D_LOAD * T4)

ALUadd = D_ADD * T4
ALUsub = D_SUB * T4

RegWrite = (D_ADD + D_SUB) * T5 + D_LOAD * T5

MemWrite = D_STORE * T5`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Hardwired Control Implementation</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`PLA (Programmable Logic Array) Implementation:

        Instruction Decoder Outputs
              |   |   |   |
              D0  D1  D2  D3
              |   |   |   |
    T0 ----+--+---+---+---+---+
           |                  |
    T1 ----+--+---+---+---+---+----> AND Plane
           |                  |
    T2 ----+--+---+---+---+---+
           |                  |
    T3 ----+--+---+---+---+---+
           |                  |
    T4 ----+--+---+---+---+---+
           |                  |
           +--+---+---+---+---+
              |   |   |   |
              v   v   v   v
           +------------------+
           |    OR Plane      |----> Control Signals
           +------------------+
              |   |   |   |
              v   v   v   v
             C1  C2  C3  C4

Advantages of PLA:
- Regular structure
- Easy to design
- Can implement any Boolean function
- Compact implementation

Alternative: ROM-based Control
- Address = {Instruction, Timing State}
- Output = Control Signals
- Technically hardwired if ROM is mask-programmed`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Advantages and Disadvantages</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Advantages</th>
            <th className="p-3 border">Disadvantages</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Very fast execution - no memory delays</td>
            <td className="p-3 border">Difficult to modify or update</td>
          </tr>
          <tr>
            <td className="p-3 border">Optimal for simple instruction sets</td>
            <td className="p-3 border">Complex design for large instruction sets</td>
          </tr>
          <tr>
            <td className="p-3 border">Lower hardware cost for simple CPUs</td>
            <td className="p-3 border">Higher design and debugging effort</td>
          </tr>
          <tr>
            <td className="p-3 border">Efficient for RISC architectures</td>
            <td className="p-3 border">Bug fixes require new chip fabrication</td>
          </tr>
          <tr>
            <td className="p-3 border">No control memory overhead</td>
            <td className="p-3 border">Adding new instructions is expensive</td>
          </tr>
          <tr>
            <td className="p-3 border">Deterministic timing</td>
            <td className="p-3 border">Large irregular circuits for complex CPUs</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Design Process</h2>
    <ol className="list-decimal list-inside leading-relaxed space-y-2 ml-4">
      <li><strong>Define Instruction Set:</strong> List all instructions and their operations</li>
      <li><strong>Identify Control Signals:</strong> Determine all control points in datapath</li>
      <li><strong>Create Timing Diagram:</strong> Define timing states for each instruction</li>
      <li><strong>Build Control Matrix:</strong> Map signals to instruction/timing combinations</li>
      <li><strong>Derive Boolean Equations:</strong> Write equations for each control signal</li>
      <li><strong>Optimize Logic:</strong> Minimize using Karnaugh maps or other methods</li>
      <li><strong>Implement Circuit:</strong> Build using gates, PLAs, or synthesized logic</li>
      <li><strong>Verify and Test:</strong> Simulate and validate all instruction sequences</li>
    </ol>

    <h2 className="text-3xl font-bold mt-8">Key Points</h2>
    <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg">
      <ul className="list-disc list-inside space-y-1">
        <li>Hardwired control uses combinational logic for signal generation</li>
        <li>Components: instruction decoder, timing generator, control logic</li>
        <li>Control signals are Boolean functions of instruction and timing</li>
        <li>Faster than microprogrammed control (no memory access)</li>
        <li>Best suited for RISC processors with simple instruction sets</li>
        <li>Difficult and expensive to modify after fabrication</li>
        <li>Can be implemented using PLAs, ROMs, or gate networks</li>
        <li>Each control signal has a Boolean equation defining when it is active</li>
      </ul>
    </div>
  </div>
);

export default HardwiredControl;
