import React from 'react';

const InterruptIO: React.FC = () => (
  <div className="p-8 space-y-6 rounded-xl shadow-lg mt-20">
    <h1 className="text-4xl font-extrabold border-b-2 pb-2">
      Interrupt Driven I/O
    </h1>
    <p className="text-sm text-gray-500">Last Updated: 13 Jan, 2026</p>

    <p className="text-lg leading-relaxed">
      Interrupt-driven I/O is an I/O technique where peripheral devices signal the CPU when
      they need attention, rather than the CPU continuously polling device status. When a
      device is ready for data transfer, it sends an interrupt signal to the CPU, which then
      suspends its current task to service the I/O request before resuming normal operation.
    </p>

    <h2 className="text-3xl font-bold mt-8">Concept of Interrupts</h2>
    <p className="leading-relaxed">
      An interrupt is a signal that temporarily halts the normal execution of a program,
      allowing the CPU to handle an event that requires immediate attention. After servicing
      the interrupt, the CPU returns to its previous task.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Interrupt-Driven I/O Overview:

Normal Execution:        Interrupt Occurs:
+---------------+        +---------------+
| Main Program  |        | Main Program  |
|    Task A     |        |    Task A     |<----+
|    Task B     |        |    Task B     |     |
|    Task C     |   =>   |    ....       |     | Return
|    Task D     |        +---------------+     |
|    ....       |              |               |
+---------------+              v (Interrupt)   |
                         +---------------+     |
                         |    ISR        |-----+
                         | (I/O Handler) |
                         +---------------+

Timeline Comparison:

Programmed I/O (Polling):
CPU: [Poll][Poll][Poll][Poll][Transfer][Main Program]
                              ^
                        Device Ready

Interrupt-Driven I/O:
CPU: [Main Program][Main Program][ISR][Main Program]
                                  ^
                            Interrupt`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Interrupt Processing Steps</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Interrupt Handling Sequence:

1. Device signals interrupt (INT line goes active)
2. CPU completes current instruction
3. CPU acknowledges interrupt (INTA signal)
4. CPU saves current state:
   - Push Program Counter (return address)
   - Push Processor Status Register (flags)
   - Save other registers if needed
5. CPU identifies interrupt source
6. CPU loads ISR address into PC
7. Execute Interrupt Service Routine (ISR)
8. ISR performs I/O operation
9. ISR executes return instruction (IRET/RTI)
10. CPU restores saved state
11. CPU resumes original program

State Saving:
                Before Interrupt        During ISR
Stack:          +------------+         +------------+
                |            |         | Old PC     | <- Return address
                |            |         | Old PSW    | <- Flags/status
                |            |         | Old Regs   | <- If saved
                +------------+         +------------+

Register File:  [Current Values]  =>   [ISR Values]
PC:             [Main Program]    =>   [ISR Address]`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Types of Interrupts</h2>

    <h3 className="text-2xl font-semibold mt-6">1. Hardware Interrupts</h3>
    <p className="leading-relaxed">
      Generated by external hardware devices through dedicated interrupt lines.
    </p>

    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Type</th>
            <th className="p-3 border">Description</th>
            <th className="p-3 border">Examples</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Maskable (INTR)</td>
            <td className="p-3 border">Can be disabled by software</td>
            <td className="p-3 border">Keyboard, disk, network</td>
          </tr>
          <tr>
            <td className="p-3 border">Non-Maskable (NMI)</td>
            <td className="p-3 border">Cannot be disabled, highest priority</td>
            <td className="p-3 border">Power failure, memory error</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h3 className="text-2xl font-semibold mt-6">2. Software Interrupts</h3>
    <p className="leading-relaxed">
      Generated by executing special instructions within a program. Used for system calls
      and exception handling.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Software Interrupt Examples:

x86 Architecture:
  INT 21h    ; DOS system call
  INT 80h    ; Linux system call
  INT 3      ; Breakpoint (debugging)

ARM Architecture:
  SWI 0      ; Software interrupt
  SVC #imm   ; Supervisor call

Exception Types:
- Division by zero
- Invalid opcode
- Page fault
- Overflow
- Breakpoint`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Interrupt Controller</h2>
    <p className="leading-relaxed">
      The Programmable Interrupt Controller (PIC) manages multiple interrupt sources,
      prioritizes them, and presents interrupts to the CPU one at a time.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`8259A Programmable Interrupt Controller:

+------------------------------------------------------+
|                    8259A PIC                         |
|                                                      |
|  IR0 ----+                                           |
|  IR1 ----+     +----------+     +-----------+        |
|  IR2 ----+--->| Priority  |--->| Interrupt  |---> INT (to CPU)
|  IR3 ----+    | Resolver  |    | Request    |        |
|  IR4 ----+    +----------+     | Register   |        |
|  IR5 ----+                     +-----------+        |
|  IR6 ----+                           |              |
|  IR7 ----+                     +-----------+        |
|                                | In-Service|        |
|  D0-D7 <====================  | Register  |        |
|  (Data Bus)                   +-----------+        |
|                                                      |
+------------------------------------------------------+

Priority (Default):
IR0: Highest priority (Timer)
IR1: Keyboard
IR2: Cascade (for second PIC)
IR3: COM2
IR4: COM1
IR5: LPT2
IR6: Floppy disk
IR7: LPT1 (Lowest priority)

Cascade Configuration (Master-Slave):
     +-------+           +-------+
     | 8259A |  IR2      | 8259A |
     |Master |<----------|Slave  |
     +-------+           +-------+
        INT                 INT
         |                   |
         v                   |
        CPU <----------------+`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Interrupt Vector Table</h2>
    <p className="leading-relaxed">
      The Interrupt Vector Table (IVT) is a table in memory containing the addresses of
      Interrupt Service Routines. Each interrupt has a unique vector number used as an
      index into this table.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Interrupt Vector Table (x86 Real Mode):

Memory Address    Vector    Purpose
+------------+
|  0000:0000 |    0        Divide Error
|  0000:0004 |    1        Single Step (Debug)
|  0000:0008 |    2        NMI
|  0000:000C |    3        Breakpoint
|  0000:0010 |    4        Overflow
|            |
|    ...     |   ...       Reserved/System
|            |
|  0000:0020 |    8        Timer (IRQ0)
|  0000:0024 |    9        Keyboard (IRQ1)
|  0000:0028 |    10       Cascade
|  0000:002C |    11       COM2 (IRQ3)
|  0000:0030 |    12       COM1 (IRQ4)
|            |
|    ...     |   ...
|            |
|  0000:03FC |    255      User defined
+------------+

Each entry contains:
- Segment:Offset (4 bytes in real mode)
- Or descriptor index (protected mode)

Vector Address Calculation:
Vector_Address = Vector_Number * 4  (real mode)
Vector_Address = Vector_Number * 8  (protected mode, IDT)`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Interrupt Service Routine (ISR)</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`ISR Structure:

keyboard_isr:
    ; Save registers
    PUSH AX
    PUSH BX
    PUSH DS

    ; Set up data segment
    MOV  AX, DATA_SEG
    MOV  DS, AX

    ; Read keyboard data
    IN   AL, 0x60           ; Read scan code
    MOV  [key_buffer], AL   ; Store in buffer

    ; Send End-of-Interrupt to PIC
    MOV  AL, 0x20
    OUT  0x20, AL           ; EOI to master PIC

    ; Restore registers
    POP  DS
    POP  BX
    POP  AX

    ; Return from interrupt
    IRET

ISR Guidelines:
1. Save all registers you modify
2. Keep ISR as short as possible
3. Don't call functions that aren't reentrant
4. Send EOI before returning (for hardware interrupts)
5. Use IRET (not RET) to return`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Interrupt Priority and Nesting</h2>
    <p className="leading-relaxed">
      When multiple interrupts occur simultaneously or during ISR execution, priority
      determines which gets serviced first. Nested interrupts allow higher-priority
      interrupts to preempt lower-priority ISRs.
    </p>

    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Priority Schemes:

1. Fixed Priority:
   Device 0 > Device 1 > Device 2 > Device 3
   (Highest)                        (Lowest)

   Problem: Low priority devices may starve

2. Rotating Priority (Round Robin):
   After servicing device n, priorities rotate
   Before: 0 > 1 > 2 > 3
   After:  1 > 2 > 3 > 0

   Advantage: Fair access for all devices

Nested Interrupts:

Main Program                 Priority: 0 (Lowest)
       |
       v
  [Interrupt A]              Priority: 2
       |
       +---> ISR_A
              |
              v
         [Interrupt B]       Priority: 3 (Higher)
              |
              +---> ISR_B
                     |
                     v
                    IRET (return to ISR_A)
              |
              v
             IRET (return to Main)

To enable nesting in ISR:
- Re-enable interrupts (STI) after saving state
- Higher priority interrupts can preempt`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Example: Keyboard Interrupt Handler</h2>
    <div className="bg-gray-100 text-gray-900 p-4 rounded-lg mt-4 text-gray-900">
      <pre className="text-sm overflow-x-auto text-gray-900">
{`Complete Keyboard Interrupt Example:

; Data segment
key_buffer:    DB 32 DUP(0)    ; Circular buffer
buffer_head:   DW 0             ; Write pointer
buffer_tail:   DW 0             ; Read pointer

; Keyboard ISR (IRQ1 = INT 9)
keyboard_handler:
    PUSH AX
    PUSH BX
    PUSH DS

    ; Set up data segment
    MOV  AX, @DATA
    MOV  DS, AX

    ; Read scan code from keyboard controller
    IN   AL, 0x60

    ; Store in circular buffer
    MOV  BX, [buffer_head]
    MOV  [key_buffer + BX], AL

    ; Update head pointer (circular)
    INC  BX
    AND  BX, 31                 ; Wrap at 32
    MOV  [buffer_head], BX

    ; Acknowledge interrupt to PIC
    MOV  AL, 0x20
    OUT  0x20, AL

    ; Restore and return
    POP  DS
    POP  BX
    POP  AX
    IRET

; Install interrupt handler
install_handler:
    CLI                         ; Disable interrupts

    ; Save old vector
    MOV  AX, 0
    MOV  ES, AX
    MOV  AX, ES:[9*4]
    MOV  [old_keyboard_handler], AX
    MOV  AX, ES:[9*4+2]
    MOV  [old_keyboard_handler+2], AX

    ; Install new vector
    MOV  WORD PTR ES:[9*4], OFFSET keyboard_handler
    MOV  WORD PTR ES:[9*4+2], SEG keyboard_handler

    STI                         ; Re-enable interrupts
    RET`}
      </pre>
    </div>

    <h2 className="text-3xl font-bold mt-8">Comparison: Polling vs Interrupts</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Aspect</th>
            <th className="p-3 border">Programmed I/O (Polling)</th>
            <th className="p-3 border">Interrupt-Driven I/O</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">CPU Utilization</td>
            <td className="p-3 border">Poor (busy waiting)</td>
            <td className="p-3 border">Good (CPU free until interrupt)</td>
          </tr>
          <tr>
            <td className="p-3 border">Response Time</td>
            <td className="p-3 border">Depends on poll frequency</td>
            <td className="p-3 border">Near immediate</td>
          </tr>
          <tr>
            <td className="p-3 border">Hardware</td>
            <td className="p-3 border">Simple</td>
            <td className="p-3 border">Requires interrupt controller</td>
          </tr>
          <tr>
            <td className="p-3 border">Software Complexity</td>
            <td className="p-3 border">Simple loops</td>
            <td className="p-3 border">ISR management, vectors</td>
          </tr>
          <tr>
            <td className="p-3 border">Multitasking</td>
            <td className="p-3 border">Difficult</td>
            <td className="p-3 border">Well supported</td>
          </tr>
          <tr>
            <td className="p-3 border">Overhead</td>
            <td className="p-3 border">Polling loop overhead</td>
            <td className="p-3 border">Context switch overhead</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Advantages and Disadvantages</h2>
    <div className="overflow-x-auto mt-4">
      <table className="min-w-full border border-gray-300 text-left">
        <thead className="bg-gray-200">
          <tr>
            <th className="p-3 border">Advantages</th>
            <th className="p-3 border">Disadvantages</th>
          </tr>
        </thead>
        <tbody className="bg-white text-gray-900">
          <tr>
            <td className="p-3 border">Efficient CPU utilization</td>
            <td className="p-3 border">Context switch overhead</td>
          </tr>
          <tr>
            <td className="p-3 border">Fast response to events</td>
            <td className="p-3 border">Complex hardware needed</td>
          </tr>
          <tr>
            <td className="p-3 border">Supports multitasking</td>
            <td className="p-3 border">Difficult to debug</td>
          </tr>
          <tr>
            <td className="p-3 border">Priority handling built-in</td>
            <td className="p-3 border">Possible interrupt storms</td>
          </tr>
          <tr>
            <td className="p-3 border">No busy waiting</td>
            <td className="p-3 border">Reentrancy issues</td>
          </tr>
        </tbody>
      </table>
    </div>

    <h2 className="text-3xl font-bold mt-8">Key Points</h2>
    <div className="bg-yellow-50 dark:bg-yellow-900/20 p-4 rounded-lg">
      <ul className="list-disc list-inside space-y-1">
        <li>Interrupt-driven I/O allows CPU to perform other work while waiting for devices</li>
        <li>Devices signal readiness via interrupt lines to the interrupt controller</li>
        <li>CPU saves state and jumps to ISR via the Interrupt Vector Table</li>
        <li>Hardware interrupts can be maskable or non-maskable</li>
        <li>Software interrupts are triggered by instructions (INT, SWI)</li>
        <li>Priority determines order of service when multiple interrupts occur</li>
        <li>Nested interrupts allow higher priority to preempt lower priority ISRs</li>
        <li>ISRs should be short, save/restore state, and send EOI before returning</li>
        <li>Significantly better CPU utilization than polling for slow devices</li>
      </ul>
    </div>
  </div>
);

export default InterruptIO;
